### ISSUE TITLE
Deflation of an area of interest

### ISSUE THREAD

**Issue by michaelbernini** [KVSlab/morphMan#77]
Hi,
I'm trying to obtain a deflation of an area of interest exploiting morphMan via Anaconda prompt.
The vmtk renderer launches normally, but after I choose the start and end points for the AOI and quit the renderer, the following issue appears:
![morphman issue](https://user-images.githubusercontent.com/114572246/192746244-70ae6795-0ff7-4acb-b7b2-5825ae6f3cde.png)
![areaofinterest](https://user-images.githubusercontent.com/114572246/192747933-e07201aa-d6aa-4f48-ac5d-ad562e6fe7c4.png)

Any tips for solving this issue?
Thanks in advance,
Michael

**Comment by hkjeldsberg** [comment]
Hi @michaelbernini ,

Thanks for reporting this issue. Seems to me like it has some issues while computing the centerlines. If you could provide the model, I can have a closer look and see if I figure out what is causing the error. 

Best,
Henrik

**Comment by michaelbernini** [comment]
Hi @hkjeldsberg ,
I shared the file of the model with you via email. Thank you for the help!
Michael

**Comment by hkjeldsberg** [comment]
Hi again @michaelbernini ,

Thanks for sharing the model with me! The error was during preparation of the output surface, which I should have fixed in PR #78 . I will merge this to master as soon as the tests pass.

Using this fix and the following command: 
```
morphman-area -i model.vtp -o output.vtp --method area --percentage -20 --region-of-interest commandline --region-points 20.00 19.418 2.63 20.32 19.13 -1.28 --poly-ball-size 100 100 100
```
resulted in the manipulated model shown in the attached figure (white original, red manipulated):
![area_fixed](https://user-images.githubusercontent.com/9609456/192822612-e950b371-5dc6-4add-bb67-2659abeaeb5a.png)

Hope this helps! 

Best,
Henrik

**Comment by michaelbernini** [comment]
Hi @hkjeldsberg ,
It worked perfectly, thank you for your help!

**Comment by hkjeldsberg** [comment]
Hi @michaelbernini ,

Great! Happy to help. 

Closing this issue. 

Best,
Henrik
